### ISSUE TITLE
api post error 500

### ISSUE THREAD

**Issue by zahroul** [PentagonalProject/rest#1]
Got this error after migrate db into my local postgre
`Array ( 
[type] => 1 
[message] => Uncaught Error: Class 'PentagonalProject\App\Rest\Override\PhpError' not found in /home/ulum/HTTP/HOST/rest.dev/Components/Containers/Global/PhpErrorHandler.php:22 Stack trace: #0 /home/ulum/HTTP/HOST/rest.dev/vendor/pimple/pimple/src/Pimple/Container.php(118): PentagonalProject\App\Rest\Record\AppFacade->{closure}(Object(Slim\Container)) #1 /home/ulum/HTTP/HOST/rest.dev/vendor/slim/slim/Slim/Container.php(123): Pimple\Container->offsetGet('phpErrorHandler') #2 /home/ulum/HTTP/HOST/rest.dev/vendor/slim/slim/Slim/App.php(669): Slim\Container->get('phpErrorHandler') #3 /home/ulum/HTTP/HOST/rest.dev/vendor/slim/slim/Slim/App.php(374): Slim\App->handlePhpError(Object(Error), Object(Slim\Http\Request), Object(Slim\Http\Response)) #4 /home/ulum/HTTP/HOST/rest.dev/vendor/slim/slim/Slim/App.php(295): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response)) #5 /home/ulum/HTTP/HOST/rest.dev/Web/Rest/index.php(48): Slim\App->run() #6 {main} thrown [file] => /home/ulum/HTTP/HOST/rest.dev/Components/Containers/Global/PhpErrorHandler.php [line] => 22 )`

**Comment by zahroul** [comment]
Error has changed
`Array ( [type] => 8192 [message] => call_user_func() expects parameter 1 to be a valid callback, non-static method PentagonalProject\Modules\Recipicious\Task\RecipeRoute::postIndex() should not be called statically [file] => /home/ulum/HTTP/HOST/rest.dev/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php [line] => 41 )`

**Comment by zahroul** [comment]
Maybe this is the error source
https://github.com/PentagonalProject/rest/blob/5c5219ba61b0954959492aecf0e2009841dadc21/Components/Modules/Recipicious/Libs/Api.php#L163

**Comment by pentagonal** [comment]
Case Problem

https://github.com/PentagonalProject/rest/blob/5c5219ba61b0954959492aecf0e2009841dadc21/Components/Modules/Recipicious/Tasks/MainWorker.php#L141

**Comment by pentagonal** [comment]
https://github.com/PentagonalProject/rest/blob/58825966352383fc5e034e333c56538a24019522/Components/Modules/Recipicious/Tasks/MainWorker.php#L139

Solved New Commit 
58825966352383fc5e034e333c56538a24019522

**Comment by zahroul** [comment]
Ojo ditutup disek, sek ada error sing message kyk ngene
`Argument 3 passed to PentagonalProject\\Modules\\Recipicious\\Lib\\Api::map() must be callable, string given`
Hahaha

**Comment by pentagonal** [comment]
wkkwkwkw sek sek mosoke wkwkw

**Comment by zahroul** [comment]
@pentagonal tenan lik, suwer, kesamber gethuk

**Comment by pentagonal** [comment]
99a8e9df0b02bbf9b6370d1c87f3e36dcf1df78d
wes tes coba wkkwkw

**Comment by zahroul** [comment]
@pentagonal 👌🏻 Fix tutup

**Comment by pentagonal** [comment]
Problem Case :  https://github.com/PentagonalProject/rest/issues/1#issuecomment-323337544

Has been Solved And use Features with commit

8ca3b8b816cf13865872ab8ff0e1ffcefce72acd

on: 

https://github.com/PentagonalProject/rest/blob/8ca3b8b816cf13865872ab8ff0e1ffcefce72acd/App/Core/Abstracts/RouteMapperBaseAbstract.php#L108

called in : 
https://github.com/PentagonalProject/rest/blob/8ca3b8b816cf13865872ab8ff0e1ffcefce72acd/App/Core/Abstracts/RouteMapperBaseAbstract.php#L83
